### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by makipsee** [JoryHogeveen/home-assistant-merge-db#6]
im trying to run this through portainer. i changed the port since portainer uses 9000 and when i try to access the page i get this

"Forbidden
You don't have permission to access this resource.

Apache/2.4.62 (Debian) Server at 192.168.1.254 Port 7000"

**Comment by JoryHogeveen** [comment]
Besides not having touched this code for over 2 years I've personally never used Docker for this as it was a user contribution later on.
Did you still point to the internal port 80? So config would be: `- 7000:80`

**Comment by makipsee** [comment]
ahhh ok yea that sounds like my luck haha. 

yes thats how it is setup

**Comment by JoryHogeveen** [comment]
Just tried running it myself through Docker on a different port and that went well. No idea why that would matter but I used port 9123.
I did get a notice asking to allow Docker access to the local resource (src folder) which you need to accept, could that be the issue?

**Comment by makipsee** [comment]
i ended up running downloading it and running right from the folder (not within portainer) and it works but it doesnt work haha. i choose the corrupted file in DB OLD and the current file in DB NEW and when i click run nothing happens lol

**Comment by JoryHogeveen** [comment]
Good that you've got the project running, in regards to the other issue it's most likely a SQL structure problem.
I see you've already went to the topic which covers this so I'm closing this topic.
